/*<auto-generated>
	This code generated from Convertor library at 28.01.2024 03:49:06
</auto-generated>
*/

namespace SkillHavenDB;

public class BlogComments
{
    public int BlogCommentsId;
    public int BlogId;
    public string CommentContent;
    public string CommentTitle;
    public bool isPublished;
    public DateTime PublishDate;
    public int UserId;
    public Blogs Blogs;
}
public class Blogs
{
    public int BlogId;
    public BlogTopics BlogTopics;
    public Users Users;
    public ICollection<BlogComments> BlogComments;
}
public class BlogTopics
{
    public int BlogTopicId;
    public bool? IsActive;
    public string TopicName;
    public ICollection<Blogs> Blogs;
}
public class BlogVotes
{
    public int? BlogId;
    public long BlogVoteId;
    public int? UserId;
    public bool? VoteValue;
    public Users Users;
}
public class ChatUser
{
    public int Id;
    public DateTime LastSeen;
    public string? ProfilePicture;
    public string? Status;
    public int UserId;
}
public class Consultant
{
    public int ConsultantId;
    public string? Description;
    public int Experience;
    public decimal? Rating;
    public int UserId;
    public Users Users;
}
public class Message
{
    public string? MessageContent;
    public int MessageId;
    public string? MessageType;
    public int? ReceiverId;
    public string? SeenStatus;
    public int? SenderId;
    public DateTime Timestamp;
}
public class Supervisors
{
    public string? Description;
    public string Expertise;
    public decimal? Rating;
    public int SupervisorId;
    public int UserId;
    public Users Users;
}
public class UserConnection
{
    public int ChatUserId;
    public DateTime? ConnectedTime;
    public string ConnectionId;
    public int Id;
}
public class Users
{
    public string Email;
    public string FirstName;
    public bool? HasMailConfirm;
    public bool IsDeleted;
    public string LastName;
    public string? MailConfirmationCode;
    public string Password;
    public string? ProfilePicture;
    public string Role;
    public int UserId;
    public ICollection<Blogs> Blogs;
    public ICollection<BlogVotes> BlogVotes;
    public ICollection<Consultant> Consultant;
    public ICollection<Supervisors> Supervisors;
}
